name = "worker-multitenants-directoriopaisa"
main = "index.ts"
compatibility_date = "2023-10-30"

routes = [
  { pattern = "*copaguia.com/*", zone_name = "copaguia.com" },
  { pattern = "*niquia.com/*", zone_name = "niquia.com" },
  { pattern = "*elhueco.online/*", zone_name = "elhueco.online" }
]
